[package]
name = "alephvault_evm_gdextension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ethers-core = "2"
ethers-signers = "2"
futures = "0.3"
godot = "0.2"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
serde_json = "1"
tiny-keccak = { version = "2", features = ["keccak"] }
ureq = { version = "2", features = ["json"] }
